# 这里是Markdown单元格

In [1]:
import torch

print("Hello World, Hello PyTorch {}".format(torch.__version__))

print("\nCUDA is available:{}, version is {}".format(torch.cuda.is_available(), torch.version.cuda))

print("\ndevice_name: {}".format(torch.cuda.get_device_name(0)))

Hello World, Hello PyTorch 2.3.0+cu121

CUDA is available:True, version is 12.1

device_name: NVIDIA GeForce RTX 4070 Ti SUPER


# 连个神奇操作
! 以及 %% 使用

In [8]:
!nvidia-smi; echo

# !time /t
! date; echo

!dir

Sun May 19 13:57:23 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.67                 Driver Version: 550.67         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    Off |   00000000:01:00.0 Off |                  N/A |
|  0%   46C    P8             12W /  285W |    3176MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
%%timeit
a = []
for i in range(10):
    a.append(i)

141 ns ± 0.331 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [4]:
%%time
a = []
for i in range(1000000):
    a.append(i)

CPU times: user 34.8 ms, sys: 2.82 ms, total: 37.6 ms
Wall time: 37.3 ms


In [11]:
import torch

print(torch.linspace(3, 10, steps=5))
print(torch.linspace(1, 5, steps=3))

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([1., 3., 5.])


In [9]:
print(torch.logspace(start=0.1, end=1.0, steps=5))
print(torch.logspace(start=2, end=2, steps=1, base=2))

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])
tensor([4.])


In [12]:
print(torch.eye(3))
print(torch.eye(3, 4))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
